# Generated by Django 3.2.1 on 2021-05-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_auto_20210506_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcar',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
