# Generated by Django 3.2.1 on 2021-05-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_alter_clientcar_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprice',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.car'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(max_length=20, verbose_name='Engine capacity'),
        ),
        migrations.AlterField(
            model_name='clientcar',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='Year'),
        ),
    ]
